In [149]:
import os,json
import nltk
import re

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from spellchecker import SpellChecker

lemmatizer = WordNetLemmatizer()
spell=SpellChecker()
CWD = os.getcwd()
BUG_REPORTS_DIR = os.path.join(CWD,"bugs")
BUG_REPORTS_LIST = os.listdir(BUG_REPORTS_DIR)

In [307]:
print(BUG_REPORTS_DIR)
print('-----------------')
print(BUG_REPORTS_LIST)
print('-----------------')


train_set = []
test_set = []

for count, report in enumerate(BUG_REPORTS_LIST):
    if count == 0:
        #add this project to test set
        print(f'Test Set: {report}')
        with open(os.path.join(BUG_REPORTS_DIR,report), 'r',encoding='cp850') as report_file:
            temp_data = json.load(report_file)
            print(f"File:{report} <> Reports: {len(temp_data['bugs'])}")
            test_set.extend(temp_data["bugs"])
    else:
        #appent this project to train set
        print(f'Train Set: {report}')
        with open(os.path.join(BUG_REPORTS_DIR,report), 'r',encoding='cp850') as report_file:
            temp_data = json.load(report_file)
            print(f"File:{report} <> Reports: {len(temp_data['bugs'])}")
            train_set.extend(temp_data["bugs"]) 

/home/cr/Desktop/bugs
-----------------
['Core.json', 'Toolkit.json', 'bugzilla.json', 'Calendar.json', 'SeaMonkey.json', 'Camino Graveyard.json', 'MailNews Core.json', 'Firefox.json', 'Thunderbird.json', 'Core Graveyard.json']
-----------------
Test Set: Core.json
File:Core.json <> Reports: 7228
Train Set: Toolkit.json
File:Toolkit.json <> Reports: 1899
Train Set: bugzilla.json
File:bugzilla.json <> Reports: 5324
Train Set: Calendar.json
File:Calendar.json <> Reports: 1785
Train Set: SeaMonkey.json
File:SeaMonkey.json <> Reports: 8716
Train Set: Camino Graveyard.json
File:Camino Graveyard.json <> Reports: 1290
Train Set: MailNews Core.json
File:MailNews Core.json <> Reports: 2796
Train Set: Firefox.json
File:Firefox.json <> Reports: 7368
Train Set: Thunderbird.json
File:Thunderbird.json <> Reports: 5129
Train Set: Core Graveyard.json
File:Core Graveyard.json <> Reports: 888


In [308]:
summary_train=[]
label_train=[]
summary_test=[]
label_test=[]
for i in train_set:
    summary_train.append(i['summary'])
    label_train.append(i['resolution'])
    
print('train_summary',len(summary_train))
print('train_label',len(label_train))

    #label_train=label_train[0:10]
for j in test_set:
    summary_test.append(j['summary'])
    label_test.append(j['resolution'])

print('test_summary',len(summary_test))
print('test_label',len(label_test))

train_summary 35195
train_label 35195
test_summary 7228
test_label 7228


In [298]:
lemmas=[]
lemmatized_word=[]
train_summary=[]
import inflection
for count, summaries in enumerate (summary_train):
    #print(count)
    
    r_special_c = re.sub(r'\W', ' ',summaries) 
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', r_special_c)
    
    r_s_c = re.sub(r'\^[a-zA-Z]\s+', ' ', document)
    s_m_s = re.sub(r'\s+', ' ', r_s_c, flags=re.I)
    r_prefix = re.sub(r'^b\s+', '', s_m_s)
    r_pm = re.sub(r'[^\w\s]', '', r_prefix)
    step1 = r_pm.replace("`` ", '"').replace(" ''", '"').replace('. . .',  '...')
    step2 = step1.replace(" ( ", " (").replace(" ) ", ") ")
    step3 = re.sub(r' ([.,:;?!%]+)([ \'"`])', r"\1\2", step2)
    step4 = re.sub(r' ([.,:;?!%]+)$', r"\1", step3)
    step5 = step4.replace(" '", "'").replace(" n't", "n't").replace(
         "can not", "cannot")
    step6 = step5.replace(" ` ", " '")
    step7=step6.strip()
    
    lemmas=[]
    sentences = nltk.word_tokenize(step7)
    lemmatizer = WordNetLemmatizer()
    stem_words=[]
  
    for sentence_words in sentences:
        
        if sentence_words not in stopwords.words('english'):
            text = re.sub(r'[^a-zA-Z\']', ' ', sentence_words)
            singularization=inflection.singularize(text)
            lemma = lemmatizer.lemmatize(singularization)
            #spelled=(spell.correction(lemma))
            lower=lemma.lower()
            stem_words.append(lower)
            
    untokenized_sentence= ' '.join(stem_words)
    train_summary.append(untokenized_sentence)

KeyboardInterrupt: 

In [ ]:
print(len(train_summary))
print(train_summary[0:5])

In [154]:
lemmas=[]
lemmatized_word=[]
test_summary=[]
import inflection
for count, summaries in enumerate (summary_test):
    print(count)
    
    r_special_c = re.sub(r'\W', ' ',summaries) 
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', r_special_c)
    
    r_s_c = re.sub(r'\^[a-zA-Z]\s+', ' ', document)
    s_m_s = re.sub(r'\s+', ' ', r_s_c, flags=re.I)
    r_prefix = re.sub(r'^b\s+', '', s_m_s)
    r_pm = re.sub(r'[^\w\s]', '', r_prefix)
    step1 = r_pm.replace("`` ", '"').replace(" ''", '"').replace('. . .',  '...')
    step2 = step1.replace(" ( ", " (").replace(" ) ", ") ")
    step3 = re.sub(r' ([.,:;?!%]+)([ \'"`])', r"\1\2", step2)
    step4 = re.sub(r' ([.,:;?!%]+)$', r"\1", step3)
    step5 = step4.replace(" '", "'").replace(" n't", "n't").replace(
         "can not", "cannot")
    step6 = step5.replace(" ` ", " '")
    step7=step6.strip()
    
    lemmas=[]
    sentences = nltk.word_tokenize(step7)
    
    stem_words=[]
  
    for sentence_words in sentences:
        
        if sentence_words not in stopwords.words('english'):
            text = re.sub(r'[^a-zA-Z\']', ' ', sentence_words)
            singularization=inflection.singularize(text)
            lemma = lemmatizer.lemmatize(singularization)
            #spelled=(spell.correction(lemma))
            lower=lemma.lower()
            stem_words.append(lower)
            
    untokenized_sentence= ' '.join(stem_words)
    test_summary.append(untokenized_sentence)
print(test_summary)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [155]:
print(test_summary[0:5])
print(len(test_summary))

['support display outlook meeting request appointment etc', 'in month view show event adjacent month', 'satisfy repeating event requirement', 'add identifier requirement requirement document', 'add calendar preference appearance startup list']
1785


In [156]:
train_label=[]
for x in range(len(label_train)):
    
    if label_train[x]=="FIXED":
        label_train[x]=1
    elif label_train[x]=="WONTFIX":
        label_train[x]=0
    elif label_train[x]=="INVALID":
        label_train[x]=0
    elif label_train[x]=="INCOMPLETE":
        label_train[x]=0
    elif label_train[x]=="WONTFIX":
        label_train[x]=0
    elif label_train[x]=="WORKSFORME":
        label_train[x]=0
    elif label_train[x]=="EXPIRED":
        label_train[x]=0
    elif label_train[x]=="DUPLICATE":
        label_train[x]=0
    elif label_train[x]=="":
        label_train[x]=0
    train_label.append(label_train[x])
print('train_label', len(train_label))

train_label 40638


In [309]:
test_label=[]
for x in range(len(label_test)):
    if label_test[x]=="FIXED":
        label_test[x]=1
    elif label_test[x]=="WONTFIX":
        label_test[x]=0
    elif label_test[x]=="INVALID":
        label_test[x]=0
    elif label_test[x]=="INCOMPLETE":
        label_test[x]=0
    elif label_test[x]=="WORKSFORME":
        label_test[x]=0
    elif label_test[x]=="DUPLICATE":
        label_test[x]=0
    elif label_test[x]=="":
        label_test[x]=0
    elif label_test[x]=="EXPIRED":
        label_test[x]=0
    elif label_test[x]=="MOVED":
        label_test[x]=0
    
    test_label.append(label_test[x])
print("test_labels:",len(test_label))

test_labels: 7228


In [310]:
test_label=np.array(test_label)
#test_label.value_counts()
unique_elements, counts_elements = np.unique(test_label, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Frequency of unique values of the said array:
[[   0    1]
 [4795 2433]]


In [239]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer



#vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
#X = vectorizer.fit_transform(train_summary).toarray()

vectorizer = CountVectorizer(max_features=5000, min_df=5, max_df=0.7)
train_sentences = vectorizer.fit_transform(train_summary)

In [159]:
#print(vectorizer.get_feature_names())

In [160]:
import numpy as np

print(train_sentences.shape)
train_sentences_array=train_sentences.toarray()
train_label_array=np.array(label_train)
print(len(train_label_array))

(40638, 3515)
40638


In [161]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(train_sentences_array, train_label_array)

In [162]:
test_sentences= vectorizer.transform(test_summary)

In [163]:
print(test_sentences[0].shape)
print(test_sentences[0].toarray())
test_sentence_array=test_sentences.toarray()

(1, 3515)
[[0 0 0 ... 0 0 0]]


In [164]:
predicted = clf.predict(test_sentence_array)

In [165]:
test_label_array=np.array(test_label)

In [166]:
from sklearn import metrics
print(metrics.classification_report(test_label_array, predicted))

              precision    recall  f1-score   support

           0       0.77      0.94      0.85      1343
           1       0.43      0.13      0.20       442

    accuracy                           0.74      1785
   macro avg       0.60      0.54      0.52      1785
weighted avg       0.68      0.74      0.69      1785



In [167]:
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
#from sklearn import model_selection, naive_bayes, svm
#SVM = svm.SVC(C=1.0, kernel='linear')
#SVM_clf=SVM.fit(b, label_train)
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
#SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
#SVM.fit(Train_X_Tfidf,Train_Y)

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm_clf=clf.fit(train_sentences_array,train_label_array)

In [168]:
predictions = svm_clf.predict(test_sentence_array)

In [169]:
from sklearn import metrics
print(metrics.classification_report(test_label_array, predictions))

              precision    recall  f1-score   support

           0       0.75      0.99      0.86      1343
           1       0.47      0.02      0.03       442

    accuracy                           0.75      1785
   macro avg       0.61      0.51      0.45      1785
weighted avg       0.68      0.75      0.65      1785



In [170]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(test_label_array, predictions))

[[1334    9]
 [ 434    8]]
